### ISSUE TITLE
Usage management and reporting

### ISSUE THREAD

**Issue by orweinberger** [joola/joola#502]
We need an endpoint to indicate how many events a user used and which type of event (read, write, system etc..)
- [x] Define usage and its stores
- [x] Add needed endpoints
- [x] Allow client-side plotting via tokens
- [x] Add endpoints for reporting last read/write/all
