### ISSUE TITLE
Agnostic Datastore Layer

### ISSUE THREAD

**Issue by itayw** [joola/joola#512]
joola.io is currently coupled with MongoDB for its cache store. Users push documents which are transformed and then inserted into mongo, later they query joola.io which transforms the simple json query to a standard mongo query.
MongoDB was designated as one-of-many on day one. It has many merits, but many configuration may benefit from other providers, such as: Cassandra, InfluxDB, RethinkDB, TempoDB, Traditional SQL and more. 

The purpose of this task is to de-couple joola.io from its caching provider and make it agnostic. Current API for push and query will remain the same since it's very powerful and flexible. So, JSON documents are pushed and JSON resultset is returned via query.

The current MongoDB implementation in joola.io, via `lib/mongo` will be de-coupled into a `plugin` type, so all current capabilities and API endpoints will remain intact, however adding additional `plugins` would be possible.
As part of this task, a proper documentation of the `plugin` implementation will be added, so community developed plugins would be possible.

Relates to #263, #300 

Datastore plugin assumptions:
- [x] Returns gapless date range
- [x] Beacon entry point receives un-transformed documents in an Array
- [x] Query fetch returns an Array of JSON documents.
- [x] Plugin responsible for returning a complete/merged dataset.

Tasks:
- [x] Create MongoDB plugin, joola/joola.io.datastore-mongodb#1
- [x] Create InfluxDB plugin, joola/joola.io.datastore-influxdb#1
- [x] Create RethinkDB plugin, joola/joola.io.datastore-rethinkdb#1
- [ ] Document plugin development, https://github.com/joola/joola.io/wiki/The-Datastore-Subsystem
